name: PR Merge
on: [pull_request]
permissions:
  pull-requests: write
  contents: write
jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create dot env file
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" > .env

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup yarn
        run: |
          corepack enable
          corepack prepare yarn@1.22.19 --activate

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: Type check
        run: yarn type-check
